useOneOfDiscriminatorLookup: true
additionalProperties:
  withGoMod: false
  isGoSubmodule: true
  enumClassPrefix: true
  generateInterfaces: true
files:
  custom/api_mock.mustache:
    templateType: API
    destinationFilename: _mock.go

